-- 80/20 Outbound System: Call Recording & Audit Schema Update
-- Adds call recording columns and performance indexes to Supabase calls table

BEGIN;

ALTER TABLE calls 
ADD COLUMN IF NOT EXISTS _id TEXT,
ADD COLUMN IF NOT EXISTS user_id TEXT,
ADD COLUMN IF NOT EXISTS userId TEXT,
ADD COLUMN IF NOT EXISTS lead_id TEXT,
ADD COLUMN IF NOT EXISTS leadId TEXT,
ADD COLUMN IF NOT EXISTS call_sid TEXT,
ADD COLUMN IF NOT EXISTS callSid TEXT,
ADD COLUMN IF NOT EXISTS from_number TEXT,
ADD COLUMN IF NOT EXISTS "from" TEXT,
ADD COLUMN IF NOT EXISTS to_number TEXT,
ADD COLUMN IF NOT EXISTS "to" TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'queued',
ADD COLUMN IF NOT EXISTS duration INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS recording_url TEXT,
ADD COLUMN IF NOT EXISTS recordingUrl TEXT,
ADD COLUMN IF NOT EXISTS recording_sid TEXT,
ADD COLUMN IF NOT EXISTS recordingSid TEXT,
ADD COLUMN IF NOT EXISTS recording_duration INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS recordingDuration INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS start_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS startTime TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS end_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS endTime TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_calls_user_id ON calls(user_id);
CREATE INDEX IF NOT EXISTS idx_calls_call_sid ON calls(call_sid);
CREATE INDEX IF NOT EXISTS idx_calls_created_at ON calls(created_at);

COMMIT;
